# This is a basic workflow to help you get started with Actions

name: Auto Build OpenWRT

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
    # branches: [ main ]
  # pull_request:
    # branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
        inputs:
              OutPutFiles:
                description: 'Output File Name'     
                required: true
                default: 'OpenWrt'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Installation depends
        run: |
          sudo apt update -y
          sudo apt full-upgrade -y
          sudo apt-get -y install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          
      - name: Clone source code
        run: |
          git clone https://github.com/coolsnowwolf/lede
          cd lede
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      # SSH Connect To Actions
      - name: Setup Debug Session
        uses: csexton/debugger-action@master
        
 # - name: Generate config file
        # run: |
          # cd openwrt
          # make menuconfig
          
      - name: Download package
        run: |
           make download -j8
          
      - name: Build
        run: |
          make V=s -j$(nproc)
          
      - name : Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt-$NOW
          path: openwrt/bin/targets/*/*/*.*
          
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
